# Generated by Django 4.2.5 on 2023-09-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoptionmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/image'),
        ),
    ]
