# Generated by Django 4.2.5 on 2023-09-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='id_group',
            field=models.SlugField(null=True, verbose_name='id group'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='group/image_group', verbose_name='image group'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GroupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('image', models.ImageField(upload_to='gruop/image_group')),
                ('video', models.FileField(upload_to='group/group_video')),
                ('file', models.FileField(upload_to='group/group_file')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_option', to='groupss.groupmodel')),
            ],
            options={
                'verbose_name': 'group option',
                'verbose_name_plural': 'group options',
                'db_table': 'groups-option-model',
            },
        ),
    ]
