# Generated by Django 4.2.5 on 2023-09-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupss', '0002_channalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannalModel',
        ),
    ]
