# Generated by Django 4.2.5 on 2023-09-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupss', '0002_groupmodel_id_group_groupmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
