# Generated by Django 4.2.5 on 2023-09-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupss', '0003_groupoption_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupOption',
            new_name='GroupOptionModel',
        ),
    ]
