# Generated by Django 4.2.5 on 2023-09-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupss', '0004_rename_groupoption_groupoptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='body',
        ),
        migrations.AddField(
            model_name='groupoptionmodel',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
