# Generated by Django 4.2.5 on 2023-09-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('channal_name', models.CharField(max_length=30, verbose_name='channal name')),
                ('description', models.TextField(max_length=500, verbose_name='bio channal')),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_publish', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_channal', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members_channal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'channal',
                'verbose_name_plural': 'channals',
                'db_table': 'channal-model',
            },
        ),
    ]
