# Generated by Django 4.2.5 on 2023-09-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channalmodel',
            name='id_channal',
            field=models.SlugField(null=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='channalmodel',
            name='image_channal',
            field=models.ImageField(null=True, upload_to='channal/image_channal/', verbose_name='image channal'),
        ),
        migrations.CreateModel(
            name='PostChannal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('image', models.ImageField(upload_to='channal/post_image/')),
                ('video', models.FileField(upload_to='channal/post_video')),
                ('file', models.FileField(upload_to='channal/post_file/')),
                ('channal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channal_option', to='channals.channalmodel')),
            ],
            options={
                'verbose_name': 'create_model',
                'verbose_name_plural': 'create_models',
                'abstract': False,
            },
        ),
    ]
