# Generated by Django 4.2.5 on 2023-09-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channals', '0003_remove_channalmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postchannal',
            name='content',
            field=models.TextField(null=True, verbose_name='type this here'),
        ),
        migrations.AlterField(
            model_name='channalmodel',
            name='image_channal',
            field=models.ImageField(blank=True, null=True, upload_to='channal/image_channal/', verbose_name='image channal'),
        ),
    ]
