# Generated by Django 4.2.5 on 2023-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channals', '0005_alter_postchannal_options_alter_postchannal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='postchannal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postchannal',
            name='file',
            field=models.FileField(blank=True, upload_to='channal/post_file/'),
        ),
        migrations.AlterField(
            model_name='postchannal',
            name='image',
            field=models.ImageField(blank=True, upload_to='channal/post_image/'),
        ),
        migrations.AlterField(
            model_name='postchannal',
            name='video',
            field=models.FileField(blank=True, upload_to='channal/post_video'),
        ),
    ]
