# Generated by Django 4.2.5 on 2023-09-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channals', '0006_postchannal_is_active_alter_postchannal_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleChannal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('channals.channalmodel',),
        ),
        migrations.CreateModel(
            name='RecycleChannalOption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('channals.postchannal',),
        ),
    ]
