# Generated by Django 4.2.5 on 2023-09-20 21:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_active_code_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth day'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_choose',
            field=models.CharField(choices=[('1', 'male'), ('2', 'female')], default=1, max_length=1, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Imageuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('image', models.ImageField(upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image user',
                'verbose_name_plural': 'image users',
                'db_table': 'image_user_model',
            },
        ),
    ]
