# Generated by Django 4.2.5 on 2023-09-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender_choose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender_choose',
            new_name='gender',
        ),
    ]
