# Generated by Django 4.2.5 on 2023-09-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_gender_choose_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imageuser',
            new_name='ImageuserModel',
        ),
    ]
