# Generated by Django 4.2.5 on 2023-09-24 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_imageusermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
