# Generated by Django 4.2.5 on 2023-09-21 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('body', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frchat', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tochat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
                'db_table': 'chat-model',
            },
        ),
        migrations.CreateModel(
            name='ChatOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='chat/video')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/file')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.chatmodel')),
            ],
            options={
                'verbose_name': 'chat option',
                'verbose_name_plural': 'chat options',
                'db_table': 'chat-option-model',
            },
        ),
    ]
