# Generated by Django 4.2.5 on 2023-09-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatoptionmodel',
            old_name='option',
            new_name='chat',
        ),
    ]
