# Generated by Django 4.2.5 on 2023-09-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_option_chatoptionmodel_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleChat',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chats.chatmodel',),
        ),
        migrations.CreateModel(
            name='RecycleChatOption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chats.chatoptionmodel',),
        ),
    ]
