# Generated by Django 4.2.5 on 2023-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_recyclechat_recyclechatoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
