# Generated by Django 4.2.5 on 2023-09-24 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_chatmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frchat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tochat', to=settings.AUTH_USER_MODEL),
        ),
    ]
