# Generated by Django 4.2.5 on 2023-09-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_alter_postoptionmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='post/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='post/video')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='post.postmodel')),
            ],
            options={
                'verbose_name': 'CommentOption',
                'verbose_name_plural': 'CommentOptions',
                'db_table': 'comment-option-model',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('body', models.TextField(max_length=400)),
                ('is_reply', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcomment', to='post.postmodel')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcomment', to='comment.commentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucomment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment-model',
                'ordering': ('-create_at', 'body'),
            },
        ),
        migrations.CreateModel(
            name='RecycleComment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('comment.commentmodel',),
        ),
    ]
