# Generated by Django 4.2.5 on 2023-09-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsoptionmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/image'),
        ),
    ]
