# Generated by Django 4.2.5 on 2023-10-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postmodel_user_alter_postoptionmodel_post'),
        ('comment', '0003_commentmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsoptionmodel',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.postmodel'),
        ),
    ]
